name: CI Test Pipeline

on:
  push:
    branches: [main]

jobs:
  fake-aws-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Fake AWS Credentials
        run: |
          echo "Pretending to configure AWS credentials..."
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "Done."

      - name: Simulate Deployment
        run: echo "Simulating upload to S3... (skipped actual call)"
